- name: Create group
  user:
    name: "{{ tiaas_group }}"
    state: present
  when: tiaas_create_group

- name: Create user account
  user:
    name: "{{ tiaas_user }}"
    comment: Training Infrastructure as a Service User
    group: "{{ tiaas_group }}"
    home: "{{ tiaas_dir }}"
  when: tiaas_create_user

- name: Ensure directory is available
  file:
    path: "{{ tiaas_dir }}"
    state: directory
    owner: "{{ tiaas_user }}"
    group: "{{ tiaas_group }}"
    mode: 0750

- name: Ensure config directory is available
  file:
    path: "{{ tiaas_dir }}/config"
    state: directory
    owner: "{{ tiaas_user }}"
    group: "{{ tiaas_group }}"
    mode: 0750

- name: Clone repository
  become: true
  become_user: "{{ tiaas_user }}"
  git:
    repo: "https://github.com/usegalaxy-eu/tiaas-group-join"
    dest: "{{ tiaas_dir }}/code/"
    version: "{{ tiaas_version }}"
    force: "{{ tiaas_force_checkout }}"
  notify: 'reload tiaas'


- name: Build TIaaS Configuration object
  set_fact:
    _tiaas_config:
      DEBUG: false
      db: "{{ tiaas_galaxy_db_url }}"
      redirect_location: "{{ tiaas_redirect_url }}"
      galaxy:
        cookiename: galaxysession
        idsecret: "{{ tiaas_galaxy_idsecret }}"
      trainings: "{{ tiaas_trainings }}"

- name: Send templates
  copy:
    content: "{{ _tiaas_config | to_nice_yaml(explicit_start=True) }}"
    dest: "{{ tiaas_dir }}/config/config.yaml"
    owner: "{{ tiaas_user }}"
    group: "{{ tiaas_group }}"
    mode: 0640
  notify: 'reload tiaas'

- name: Send runner script
  template:
    src: "run.sh"
    dest: "{{ tiaas_dir }}/run.sh"
    owner: "{{ tiaas_user }}"
    group: "{{ tiaas_group }}"
    mode: 0750
  notify: 'reload tiaas'

- name: Install all of the necessary dependencies
  become: true
  become_user: "{{ tiaas_user }}"
  pip:
    virtualenv: "{{ tiaas_dir }}/venv/"
    requirements: "{{ tiaas_dir }}/code/requirements.txt"
  notify: 'reload tiaas'

- name: Install systemd unit file
  template:
    src: tiaas.service
    dest: /etc/systemd/system/tiaas.service
  notify: setup tiaas systemd

- name: Allow specified users to manage tiaas
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/tiaas
    validate: 'visudo -cf %s'
    mode: 0440
  when: tiaas_manage_user is defined
