---
- name: reload tiaas
  systemd:
    state: restarted
    name: tiaas

- name: setup tiaas systemd
  systemd:
    state: started
    enabled: true
    name: tiaas
    daemon_reload: true

- name: enable tiaas socket
  ansible.builtin.systemd:
    name: tiaas.socket
    enabled: yes
